from tkinter import *
stage= Tk()
stage.title("Vivek")
rollNo= Label(text="9159",font=("Times New Roman",20))
rollNo.pack()
button= Button(text="Click me",bg='red')
button.pack()
entry= Entry()
entry.insert(END,"This is entry box")
entry.pack()
textfield=Text(height=7, width=40)
textfield.insert(END,"This is a textfield")
textfield.pack()
stage.mainloop()